name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Markdown Lint
        uses: avto-dev/markdown-lint@v1.5.0
        with:
          fix: true
          args: "**/*.md"
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '15.x'
      - name: Install dependencies
        run: npm install
      - name: Text Lint
        run: npm run lint
